services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: hunais
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: gotest
    ports:
      - "5432:5432"
    networks:
      - my_network
  
  getway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    networks:
      - my_network

      
  auth:
    build:
      context: ./auth
    ports:
      - "3001:3001"
    env_file:
      - auth.env
    networks:
      - my_network

  posts:
    build: 
      context: ./posts
    ports:
      - "3002:3002"
    env_file:
      - posts.env
    depends_on:
      - postgres
    networks:
      - my_network
  


networks:
  my_network:
    driver: bridge
    # environment:
    #   MONGO_URI: 
    #   MONGO_DB_NAME: "goDB"
    #   MONGO_COLLECTION_NAME: "USERS"
    #   ACCESS_TOKEN_SECRET: "accesstokensecret"
    #   REFRESH_TOKEN_SECRET: "refreshtokensecret"

