CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) NOT NULL,
    password VARCHAR(20) NOT NULL
);


CREATE TABLE IF NOT EXISTS posts(
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    body VARCHAR(300) NOT NULL,
    userId TEXT,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);